### ISSUE TITLE
Null pointer exception when starting

### ISSUE THREAD

**Issue by domoritz** [Docear/Desktop#459]
``` bash
$ sh docear.sh
Knopflerfish OSGi framework, version 4.1.10
Copyright 2003-2009 Knopflerfish. All Rights Reserved.

See http://www.knopflerfish.org for more information.
Loading xargs file /Applications/Docear.app/Contents/Resources/Java/./props.xargs
Loading xargs file /Applications/Docear.app/Contents/Resources/Java/./init.xargs
Installed and started: reference:file:./core/org.freeplane.core (id#1)
User properties not found, new file created
Installed: reference:file:/Applications/Docear.app/Contents/Resources/Java/./plugins/org.docear.plugin.bibtex (id#2)
Installed: reference:file:/Applications/Docear.app/Contents/Resources/Java/./plugins/org.docear.plugin.core (id#3)
Installed: reference:file:/Applications/Docear.app/Contents/Resources/Java/./plugins/org.docear.plugin.pdfutilities (id#4)
Installed: reference:file:/Applications/Docear.app/Contents/Resources/Java/./plugins/org.docear.plugin.services (id#5)
Installed: reference:file:/Applications/Docear.app/Contents/Resources/Java/./plugins/org.freeplane.plugin.bugreport (id#6)
Installed: reference:file:/Applications/Docear.app/Contents/Resources/Java/./plugins/org.freeplane.plugin.formula (id#7)
Installed: reference:file:/Applications/Docear.app/Contents/Resources/Java/./plugins/org.freeplane.plugin.latex (id#8)
Installed: reference:file:/Applications/Docear.app/Contents/Resources/Java/./plugins/org.freeplane.plugin.openmaps (id#9)
Installed: reference:file:/Applications/Docear.app/Contents/Resources/Java/./plugins/org.freeplane.plugin.script (id#10)
Installed: reference:file:/Applications/Docear.app/Contents/Resources/Java/./plugins/org.freeplane.plugin.svg (id#11)
Installed: reference:file:/Applications/Docear.app/Contents/Resources/Java/./plugins/org.freeplane.plugin.workspace (id#12)
Started: reference:file:/Applications/Docear.app/Contents/Resources/Java/./plugins/org.docear.plugin.bibtex (id#2)
Started: reference:file:/Applications/Docear.app/Contents/Resources/Java/./plugins/org.docear.plugin.core (id#3)
Started: reference:file:/Applications/Docear.app/Contents/Resources/Java/./plugins/org.docear.plugin.pdfutilities (id#4)
Started: reference:file:/Applications/Docear.app/Contents/Resources/Java/./plugins/org.docear.plugin.services (id#5)
Started: reference:file:/Applications/Docear.app/Contents/Resources/Java/./plugins/org.freeplane.plugin.bugreport (id#6)
Started: reference:file:/Applications/Docear.app/Contents/Resources/Java/./plugins/org.freeplane.plugin.formula (id#7)
Started: reference:file:/Applications/Docear.app/Contents/Resources/Java/./plugins/org.freeplane.plugin.latex (id#8)
Started: reference:file:/Applications/Docear.app/Contents/Resources/Java/./plugins/org.freeplane.plugin.openmaps (id#9)
Started: reference:file:/Applications/Docear.app/Contents/Resources/Java/./plugins/org.freeplane.plugin.script (id#10)
Started: reference:file:/Applications/Docear.app/Contents/Resources/Java/./plugins/org.freeplane.plugin.svg (id#11)
Started: reference:file:/Applications/Docear.app/Contents/Resources/Java/./plugins/org.freeplane.plugin.workspace (id#12)
Nov 28, 2014 11:39:48 AM org.freeplane.core.util.LogUtils info
INFO: language resources for en found
Uncaught error fetching image:
java.lang.NullPointerException
    at sun.awt.image.InputStreamImageSource.getDecoder(InputStreamImageSource.java:214)
    at sun.awt.image.URLImageSource.getDecoder(URLImageSource.java:159)
    at sun.awt.image.InputStreamImageSource.doFetch(InputStreamImageSource.java:263)
    at sun.awt.image.ImageFetcher.fetchloop(ImageFetcher.java:205)
    at sun.awt.image.ImageFetcher.run(ImageFetcher.java:169)
```

**Comment by hellectronic** [comment]
I installed Apple Java6 from http://support.apple.com/kb/DL1572 and it works now.

**Comment by jbravo94** [comment]
I also got the Error on macOS Mojave 10.14.3.

I have Java 1.8 installed parallel to Apple Java6. After some searching I found in this article (https://superuser.com/questions/490425/how-do-i-switch-between-java-7-and-java-6-on-os-x-10-8-2) that the home of java 1.6 can be determined by:

/usr/libexec/java_home -v 1.6.0

This command told me the Java Home of 1.6 and i exported the JAVA_HOME variable to 1.6 and it worked:

export JAVA_HOME=/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home

Then i was able to run docear (version for all OS) in the terminal (./docear.sh).
