### ISSUE TITLE
Docear doesn't start on Archlinux

### ISSUE THREAD

**Issue by peterolejua** [Docear/Desktop#507]
First my OS and java version
```
$ screenfetch
                   -`                 
                  .o+`                 peter@thamonkie
                 `ooo/                 OS: Arch Linux 
                `+oooo:                Kernel: x86_64 Linux 4.15.8-1-ARCH
               `+oooooo:               Uptime: 1h 5m
               -+oooooo+:              Packages: 759
             `/:-:++oooo+:             Shell: bash
            `/++++/+++++++:            Resolution: 2646x768
           `/++++++++++++++:           DE: LXDE
          `/+++ooooooooooooo/`         WM: OpenBox
         ./ooosssso++osssssso+`        WM Theme: Adapta-Nokto
        .oossssso-````/ossssss+`       GTK Theme: Arc-Dark [GTK2]
       -osssssso.      :ssssssso.      Icon Theme: Adwaita
      :osssssss/        osssso+++.     Font: Ubuntu 12
     /ossssssss/        +ssssooo/-     CPU: AMD E-350 @ 2x 1.6GHz [65.0°C]
   `/ossssso+/:-        -:/+osssso+-   GPU: AMD/ATI Wrestler [Radeon HD 6310]
  `+sso+:-`                 `.-/+oso:  RAM: 1745MiB / 3549MiB
 `++:.                           `-/+/
 .`                                 `/
```

```
$ java --show-version 
openjdk 9.0.4
OpenJDK Runtime Environment (build 9.0.4+11)
OpenJDK 64-Bit Server VM (build 9.0.4+11, mixed mode)
```

I installed with 
`$ yaourt docear`

then I get the following errors when I try to start it

```
$ docear
Knopflerfish OSGi framework, version 4.1.10
Copyright 2003-2009 Knopflerfish. All Rights Reserved.

See http://www.knopflerfish.org for more information.
Loading xargs file /usr/share/docear/props.xargs
Loading xargs file /usr/share/docear/init.xargs
Installed and started: reference:file:/usr/share/docear/core/org.freeplane.core (id#1)
User properties not found, new file created
Installed: reference:file:/usr/share/docear/plugins/org.docear.plugin.pdfutilities (id#2)
Installed: reference:file:/usr/share/docear/plugins/org.freeplane.plugin.openmaps (id#3)
Installed: reference:file:/usr/share/docear/plugins/org.docear.plugin.bibtex (id#4)
Installed: reference:file:/usr/share/docear/plugins/org.freeplane.plugin.formula (id#5)
Installed: reference:file:/usr/share/docear/plugins/org.freeplane.plugin.script (id#6)
Installed: reference:file:/usr/share/docear/plugins/org.docear.plugin.services (id#7)
Installed: reference:file:/usr/share/docear/plugins/org.freeplane.plugin.latex (id#8)
Installed: reference:file:/usr/share/docear/plugins/org.freeplane.plugin.workspace (id#9)
Installed: reference:file:/usr/share/docear/plugins/org.freeplane.plugin.svg (id#10)
Installed: reference:file:/usr/share/docear/plugins/org.freeplane.plugin.bugreport (id#11)
Installed: reference:file:/usr/share/docear/plugins/org.docear.plugin.core (id#12)
Started: reference:file:/usr/share/docear/plugins/org.docear.plugin.pdfutilities (id#2)
Started: reference:file:/usr/share/docear/plugins/org.freeplane.plugin.openmaps (id#3)
Started: reference:file:/usr/share/docear/plugins/org.docear.plugin.bibtex (id#4)
Started: reference:file:/usr/share/docear/plugins/org.freeplane.plugin.formula (id#5)
Started: reference:file:/usr/share/docear/plugins/org.freeplane.plugin.script (id#6)
Started: reference:file:/usr/share/docear/plugins/org.docear.plugin.services (id#7)
Started: reference:file:/usr/share/docear/plugins/org.freeplane.plugin.latex (id#8)
Started: reference:file:/usr/share/docear/plugins/org.freeplane.plugin.workspace (id#9)
Started: reference:file:/usr/share/docear/plugins/org.freeplane.plugin.svg (id#10)
Started: reference:file:/usr/share/docear/plugins/org.freeplane.plugin.bugreport (id#11)
Started: reference:file:/usr/share/docear/plugins/org.docear.plugin.core (id#12)
mar. 12, 2018 11:21:37 A.M. org.freeplane.core.util.LogUtils info
INFORMACIÓN: language resources for es found
mar. 12, 2018 11:21:39 A.M. org.freeplane.core.util.LogUtils info
INFORMACIÓN: freeplane_version = 1.3.2 alpha; freeplane_xml_version = freeplane 1.3.0
git revision = 547e9af_Anwender_2015-08-021946550200
java_version = 9.0.4; os_name = Linux; os_version = 4.15.8-1-ARCH
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.pushingpixels.flamingo.api.ribbon.JRibbonFrame$KeyTipLayer to method com.sun.awt.AWTUtilities.setComponentMixingCutoutShape(java.awt.Component,java.awt.Shape)
WARNING: Please consider reporting this to the maintainers of org.pushingpixels.flamingo.api.ribbon.JRibbonFrame$KeyTipLayer
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
mar. 12, 2018 11:21:46 A.M. org.freeplane.core.util.LogUtils info
INFORMACIÓN: added parsing support for standard date format d/MM/yy
mar. 12, 2018 11:21:46 A.M. org.freeplane.core.util.LogUtils info
INFORMACIÓN: added parsing support for standard date time format d/MM/yy, h:mm a
mar. 12, 2018 11:21:51 A.M. org.freeplane.core.util.LogUtils info
INFORMACIÓN: Workspace controller installed.
mar. 12, 2018 11:21:51 A.M. org.freeplane.core.util.LogUtils info
INFORMACIÓN: org.docear.plugin.core.CoreConfiguration() initializing...
mar. 12, 2018 11:21:51 A.M. org.freeplane.core.util.LogUtils info
INFORMACIÓN: Docear version: 1.2.0.0 stable build 291
mar. 12, 2018 11:21:51 A.M. org.freeplane.core.util.LogUtils info
INFORMACIÓN: OS version: Linux 4.15.8-1-ARCH amd64
mar. 12, 2018 11:21:51 A.M. org.freeplane.core.util.LogUtils info
INFORMACIÓN: Loaded properties from bundle://12.0:0/org/docear/plugin/core/defaults.properties
mar. 12, 2018 11:21:53 A.M. org.freeplane.core.util.LogUtils info
INFORMACIÓN: Docear Core controller extension initiated.
mar. 12, 2018 11:21:53 A.M. org.freeplane.core.util.LogUtils info
INFORMACIÓN: Docear Services controller extension initiated.
mar. 12, 2018 11:21:53 A.M. org.freeplane.core.util.LogUtils info
INFORMACIÓN: Loaded properties from bundle://5.0:0/org/freeplane/plugin/formula/defaults.properties
mar. 12, 2018 11:21:53 A.M. org.freeplane.core.util.LogUtils info
INFORMACIÓN: Loaded properties from bundle://6.0:0/org/freeplane/plugin/script/defaults.properties
mar. 12, 2018 11:21:55 A.M. org.freeplane.core.util.LogUtils info
INFORMACIÓN: Loaded properties from bundle://7.0:0/org/docear/plugin/services/defaults.properties
mar. 12, 2018 11:21:55 A.M. org.freeplane.core.util.LogUtils info
INFORMACIÓN: Workspace settings not found, create new file
mar. 12, 2018 11:21:55 A.M. org.freeplane.core.util.LogUtils info
INFORMACIÓN: Docear Service feature installed: org.docear.plugin.services.features.user.workspace.DocearWorkspaceSettings
mar. 12, 2018 11:21:57 A.M. org.freeplane.core.util.LogUtils info
INFORMACIÓN: Docear Service feature installed: org.docear.plugin.services.features.io.DocearConnectionProvider

STDERR: java.lang.NoClassDefFoundError: org/omg/CORBA/portable/UnknownException
STDERR: 	at org.docear.plugin.services.features.user.DocearUserController.<init>(DocearUserController.java:42)
STDERR: 	at org.docear.plugin.services.ServiceController.initialize(ServiceController.java:86)
STDERR: 	at org.docear.plugin.services.Activator.startService(Activator.java:29)
STDERR: 	at org.docear.plugin.core.Activator.startPluginServices(Activator.java:67)
STDERR: 	at org.docear.plugin.core.Activator.startPlugin(Activator.java:35)
STDERR: 	at org.freeplane.plugin.workspace.Activator.startPluginServices(Activator.java:83)
STDERR: 	at org.freeplane.plugin.workspace.Activator$2.installExtension(Activator.java:45)
STDERR: 	at org.freeplane.main.osgi.ActivatorImpl.startFramework(ActivatorImpl.java:208)
STDERR: 	at org.freeplane.main.osgi.ActivatorImpl.start(ActivatorImpl.java:79)
STDERR: 	at org.freeplane.main.osgi.Activator.start(Activator.java:36)
STDERR: 	at org.knopflerfish.framework.BundleImpl.start0(BundleImpl.java:374)
STDERR: 	at org.knopflerfish.framework.PermissionOps.callStart0(PermissionOps.java:215)
STDERR: 	at org.knopflerfish.framework.BundleImpl.start(BundleImpl.java:321)
STDERR: 	at org.knopflerfish.framework.StartLevelImpl.increaseStartLevel(StartLevelImpl.java:285)
STDERR: 	at org.knopflerfish.framework.StartLevelImpl$1.run(StartLevelImpl.java:217)
STDERR: 	at org.knopflerfish.framework.StartLevelImpl.run(StartLevelImpl.java:178)
STDERR: 	at java.base/java.lang.Thread.run(Thread.java:844)
STDERR: Caused by: java.lang.ClassNotFoundException: org.omg.CORBA.portable.UnknownException
STDERR: 	at org.knopflerfish.framework.BundleClassLoader.findClass(BundleClassLoader.java:339)
STDERR: 	at org.knopflerfish.framework.BundleClassLoader.loadClass(BundleClassLoader.java:438)
STDERR: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
STDERR: 	... 17 more
STDOUT: ## DEBUG: errors - FrameworkErrorEvent bundle #1
STDOUT: ## DEBUG: errors - FrameworkErrorEvent throwable: 
STDERR: org.osgi.framework.BundleException: BundleActivator start failed
STDERR: 	at org.knopflerfish.framework.BundleImpl.start0(BundleImpl.java:419)
STDERR: 	at org.knopflerfish.framework.PermissionOps.callStart0(PermissionOps.java:215)
STDERR: 	at org.knopflerfish.framework.BundleImpl.start(BundleImpl.java:321)
STDERR: 	at org.knopflerfish.framework.StartLevelImpl.increaseStartLevel(StartLevelImpl.java:285)
STDERR: 	at org.knopflerfish.framework.StartLevelImpl$1.run(StartLevelImpl.java:217)
STDERR: 	at org.knopflerfish.framework.StartLevelImpl.run(StartLevelImpl.java:178)
STDERR: 	at java.base/java.lang.Thread.run(Thread.java:844)
STDERR: Caused by: java.lang.NoClassDefFoundError: org/omg/CORBA/portable/UnknownException
STDERR: 	at org.docear.plugin.services.features.user.DocearUserController.<init>(DocearUserController.java:42)
STDERR: 	at org.docear.plugin.services.ServiceController.initialize(ServiceController.java:86)
STDERR: 	at org.docear.plugin.services.Activator.startService(Activator.java:29)
STDERR: 	at org.docear.plugin.core.Activator.startPluginServices(Activator.java:67)
STDERR: 	at org.docear.plugin.core.Activator.startPlugin(Activator.java:35)
STDERR: 	at org.freeplane.plugin.workspace.Activator.startPluginServices(Activator.java:83)
STDERR: 	at org.freeplane.plugin.workspace.Activator$2.installExtension(Activator.java:45)
STDERR: 	at org.freeplane.main.osgi.ActivatorImpl.startFramework(ActivatorImpl.java:208)
STDERR: 	at org.freeplane.main.osgi.ActivatorImpl.start(ActivatorImpl.java:79)
STDERR: 	at org.freeplane.main.osgi.Activator.start(Activator.java:36)
STDERR: 	at org.knopflerfish.framework.BundleImpl.start0(BundleImpl.java:374)
STDERR: 	... 6 more
STDERR: Caused by: java.lang.ClassNotFoundException: org.omg.CORBA.portable.UnknownException
STDERR: 	at org.knopflerfish.framework.BundleClassLoader.findClass(BundleClassLoader.java:339)
STDERR: 	at org.knopflerfish.framework.BundleClassLoader.loadClass(BundleClassLoader.java:438)
STDERR: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
STDERR: 	... 17 more
STDOUT: Nested bundle exception:
STDERR: java.lang.NoClassDefFoundError: org/omg/CORBA/portable/UnknownException
STDERR: 	at org.docear.plugin.services.features.user.DocearUserController.<init>(DocearUserController.java:42)
STDERR: 	at org.docear.plugin.services.ServiceController.initialize(ServiceController.java:86)
STDERR: 	at org.docear.plugin.services.Activator.startService(Activator.java:29)
STDERR: 	at org.docear.plugin.core.Activator.startPluginServices(Activator.java:67)
STDERR: 	at org.docear.plugin.core.Activator.startPlugin(Activator.java:35)
STDERR: 	at org.freeplane.plugin.workspace.Activator.startPluginServices(Activator.java:83)
STDERR: 	at org.freeplane.plugin.workspace.Activator$2.installExtension(Activator.java:45)
STDERR: 	at org.freeplane.main.osgi.ActivatorImpl.startFramework(ActivatorImpl.java:208)
STDERR: 	at org.freeplane.main.osgi.ActivatorImpl.start(ActivatorImpl.java:79)
STDERR: 	at org.freeplane.main.osgi.Activator.start(Activator.java:36)
STDERR: 	at org.knopflerfish.framework.BundleImpl.start0(BundleImpl.java:374)
STDERR: 	at org.knopflerfish.framework.PermissionOps.callStart0(PermissionOps.java:215)
STDERR: 	at org.knopflerfish.framework.BundleImpl.start(BundleImpl.java:321)
STDERR: 	at org.knopflerfish.framework.StartLevelImpl.increaseStartLevel(StartLevelImpl.java:285)
STDERR: 	at org.knopflerfish.framework.StartLevelImpl$1.run(StartLevelImpl.java:217)
STDERR: 	at org.knopflerfish.framework.StartLevelImpl.run(StartLevelImpl.java:178)
STDERR: 	at java.base/java.lang.Thread.run(Thread.java:844)
STDERR: Caused by: java.lang.ClassNotFoundException: org.omg.CORBA.portable.UnknownException
STDERR: 	at org.knopflerfish.framework.BundleClassLoader.findClass(BundleClassLoader.java:339)
STDERR: 	at org.knopflerfish.framework.BundleClassLoader.loadClass(BundleClassLoader.java:438)
STDERR: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
STDERR: 	... 17 more
STDOUT: Framework launched
```

**Comment by koppor** [comment]
Similar to JabRef, Docear dies not run in Java9. Please use Java8.

Refs https://github.com/JabRef/jabref/issues/2594

Am 12.03.2018 17:24 schrieb "Peter Olejua" <notifications@github.com>:

**Comment by peterolejua** [comment]
Thanks for the reply. I changed to jre7. Now working...
