### ISSUE TITLE
[SOLVED] Docear does not launch even with java8 in voidlinux

### ISSUE THREAD

**Issue by zenny** [Docear/Desktop#517]
Hi,

I tried to run Docear with java8 in voidlinux:

```
...
STDERR: java.lang.NoClassDefFoundError: org/omg/CORBA/portable/UnknownException
STDERR: 	at org.docear.plugin.services.features.user.DocearUserController.<init>(DocearUserController.java:42)
STDERR: 	at org.docear.plugin.services.ServiceController.initialize(ServiceController.java:86)
STDERR: 	at org.docear.plugin.services.Activator.startService(Activator.java:29)
STDERR: 	at org.docear.plugin.core.Activator.startPluginServices(Activator.java:67)
STDERR: 	at org.docear.plugin.core.Activator.startPlugin(Activator.java:35)
STDERR: 	at org.freeplane.plugin.workspace.Activator.startPluginServices(Activator.java:83)
STDERR: 	at org.freeplane.plugin.workspace.Activator$2.installExtension(Activator.java:45)
STDERR: 	at org.freeplane.main.osgi.ActivatorImpl.startFramework(ActivatorImpl.java:208)
STDERR: 	at org.freeplane.main.osgi.ActivatorImpl.start(ActivatorImpl.java:79)
STDERR: 	at org.freeplane.main.osgi.Activator.start(Activator.java:36)
STDERR: 	at org.knopflerfish.framework.BundleImpl.start0(BundleImpl.java:374)
STDERR: 	at org.knopflerfish.framework.PermissionOps.callStart0(PermissionOps.java:215)
STDERR: 	at org.knopflerfish.framework.BundleImpl.start(BundleImpl.java:321)
STDERR: 	at org.knopflerfish.framework.StartLevelImpl.increaseStartLevel(StartLevelImpl.java:285)
STDERR: 	at org.knopflerfish.framework.StartLevelImpl$1.run(StartLevelImpl.java:217)
STDERR: 	at org.knopflerfish.framework.StartLevelImpl.run(StartLevelImpl.java:178)
STDERR: 	at java.base/java.lang.Thread.run(Thread.java:834)
STDERR: Caused by: java.lang.ClassNotFoundException: org.omg.CORBA.portable.UnknownException
STDERR: 	at org.knopflerfish.framework.BundleClassLoader.findClass(BundleClassLoader.java:339)
STDERR: 	at org.knopflerfish.framework.BundleClassLoader.loadClass(BundleClassLoader.java:438)
STDERR: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
STDERR: 	... 17 more
STDOUT: ## DEBUG: errors - FrameworkErrorEvent bundle #1
STDOUT: ## DEBUG: errors - FrameworkErrorEvent throwable: 
STDERR: org.osgi.framework.BundleException: BundleActivator start failed
STDERR: 	at org.knopflerfish.framework.BundleImpl.start0(BundleImpl.java:419)
STDERR: 	at org.knopflerfish.framework.PermissionOps.callStart0(PermissionOps.java:215)
STDERR: 	at org.knopflerfish.framework.BundleImpl.start(BundleImpl.java:321)
STDERR: 	at org.knopflerfish.framework.StartLevelImpl.increaseStartLevel(StartLevelImpl.java:285)
STDERR: 	at org.knopflerfish.framework.StartLevelImpl$1.run(StartLevelImpl.java:217)
STDERR: 	at org.knopflerfish.framework.StartLevelImpl.run(StartLevelImpl.java:178)
STDERR: 	at java.base/java.lang.Thread.run(Thread.java:834)
STDERR: Caused by: java.lang.NoClassDefFoundError: org/omg/CORBA/portable/UnknownException
STDERR: 	at org.docear.plugin.services.features.user.DocearUserController.<init>(DocearUserController.java:42)
STDERR: 	at org.docear.plugin.services.ServiceController.initialize(ServiceController.java:86)
STDERR: 	at org.docear.plugin.services.Activator.startService(Activator.java:29)
STDERR: 	at org.docear.plugin.core.Activator.startPluginServices(Activator.java:67)
STDERR: 	at org.docear.plugin.core.Activator.startPlugin(Activator.java:35)
STDERR: 	at org.freeplane.plugin.workspace.Activator.startPluginServices(Activator.java:83)
STDERR: 	at org.freeplane.plugin.workspace.Activator$2.installExtension(Activator.java:45)
STDERR: 	at org.freeplane.main.osgi.ActivatorImpl.startFramework(ActivatorImpl.java:208)
STDERR: 	at org.freeplane.main.osgi.ActivatorImpl.start(ActivatorImpl.java:79)
STDERR: 	at org.freeplane.main.osgi.Activator.start(Activator.java:36)
STDERR: 	at org.knopflerfish.framework.BundleImpl.start0(BundleImpl.java:374)
STDERR: 	... 6 more
STDERR: Caused by: java.lang.ClassNotFoundException: org.omg.CORBA.portable.UnknownException
STDERR: 	at org.knopflerfish.framework.BundleClassLoader.findClass(BundleClassLoader.java:339)
STDERR: 	at org.knopflerfish.framework.BundleClassLoader.loadClass(BundleClassLoader.java:438)
STDERR: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
STDERR: 	... 17 more
STDOUT: Nested bundle exception:
STDERR: java.lang.NoClassDefFoundError: org/omg/CORBA/portable/UnknownException
STDERR: 	at org.docear.plugin.services.features.user.DocearUserController.<init>(DocearUserController.java:42)
STDERR: 	at org.docear.plugin.services.ServiceController.initialize(ServiceController.java:86)
STDERR: 	at org.docear.plugin.services.Activator.startService(Activator.java:29)
STDERR: 	at org.docear.plugin.core.Activator.startPluginServices(Activator.java:67)
STDERR: 	at org.docear.plugin.core.Activator.startPlugin(Activator.java:35)
STDERR: 	at org.freeplane.plugin.workspace.Activator.startPluginServices(Activator.java:83)
STDERR: 	at org.freeplane.plugin.workspace.Activator$2.installExtension(Activator.java:45)
STDERR: 	at org.freeplane.main.osgi.ActivatorImpl.startFramework(ActivatorImpl.java:208)
STDERR: 	at org.freeplane.main.osgi.ActivatorImpl.start(ActivatorImpl.java:79)
STDERR: 	at org.freeplane.main.osgi.Activator.start(Activator.java:36)
STDERR: 	at org.knopflerfish.framework.BundleImpl.start0(BundleImpl.java:374)
STDERR: 	at org.knopflerfish.framework.PermissionOps.callStart0(PermissionOps.java:215)
STDERR: 	at org.knopflerfish.framework.BundleImpl.start(BundleImpl.java:321)
STDERR: 	at org.knopflerfish.framework.StartLevelImpl.increaseStartLevel(StartLevelImpl.java:285)
STDERR: 	at org.knopflerfish.framework.StartLevelImpl$1.run(StartLevelImpl.java:217)
STDERR: 	at org.knopflerfish.framework.StartLevelImpl.run(StartLevelImpl.java:178)
STDERR: 	at java.base/java.lang.Thread.run(Thread.java:834)
STDERR: Caused by: java.lang.ClassNotFoundException: org.omg.CORBA.portable.UnknownException
STDERR: 	at org.knopflerfish.framework.BundleClassLoader.findClass(BundleClassLoader.java:339)
STDERR: 	at org.knopflerfish.framework.BundleClassLoader.loadClass(BundleClassLoader.java:438)
STDERR: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
STDERR: 	... 17 more
STDOUT: Framework launched
```

According to #507 and http://www.docear.org/support/forums/docear-support-forums-group3/bug-reports-forum6/docear-does-not-start-on-archlinux-thread1583/, it has to do with Java version. But in my case openjdk-jre 8 is activated via asdf locally.

```
$ java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.242-b08, mixed mode)
```
Thus it does not seem java version issue in my case. Any input?

Cheers,
/z

**Comment by zenny** [comment]
SOLVED: Installing Java 7 worked:
 
```
# xbps-install -S openjdk7-bootstrap
```

Once installed, I exported the java environment for the specific instance:

```
$ JAVA_HOME="/usr/lib/jvm/java-1.7-openjdk/jre" ./docear.sh
```

It worked.

NB: Docear 1.2 appears not to work with anything above java v7.
