### ISSUE TITLE
[SOLVED] Docear Stuck on Opening Logo, Kubuntu 20.04 LTS 

### ISSUE THREAD

**Issue by qwertyuser1983** [Docear/Desktop#523]
Trying the Ubuntu version of Docear, on fresh install, but somehow there is nothing shown, the apps stuck at splash screen. There is nothing on the task bar either, but The Java is running. 

![image](https://user-images.githubusercontent.com/22538918/112726172-a433a080-8f4e-11eb-8fdd-149f210e8974.png)
![image](https://user-images.githubusercontent.com/22538918/112726302-39cf3000-8f4f-11eb-8688-5893c9f0d81c.png)

I try again running the apps on konsole, and here the output.

```
Knopflerfish OSGi framework, version 4.1.10
Copyright 2003-2009 Knopflerfish. All Rights Reserved.

See http://www.knopflerfish.org for more information.
Loading xargs file /home/renan/InstalledApps/docear-1.2.0.0_stable_build291/props.xargs
Loading xargs file /home/renan/InstalledApps/docear-1.2.0.0_stable_build291/init.xargs
Installed and started: reference:file:/home/renan/InstalledApps/docear-1.2.0.0_stable_build291/core/org.freeplane.core (id#1)
User properties not found, new file created
Installed: reference:file:/home/renan/InstalledApps/docear-1.2.0.0_stable_build291/plugins/org.freeplane.plugin.script (id#2)
Installed: reference:file:/home/renan/InstalledApps/docear-1.2.0.0_stable_build291/plugins/org.freeplane.plugin.openmaps (id#3)
Installed: reference:file:/home/renan/InstalledApps/docear-1.2.0.0_stable_build291/plugins/org.docear.plugin.core (id#4)
Installed: reference:file:/home/renan/InstalledApps/docear-1.2.0.0_stable_build291/plugins/org.freeplane.plugin.formula (id#5)
Installed: reference:file:/home/renan/InstalledApps/docear-1.2.0.0_stable_build291/plugins/org.freeplane.plugin.svg (id#6)
Installed: reference:file:/home/renan/InstalledApps/docear-1.2.0.0_stable_build291/plugins/org.docear.plugin.bibtex (id#7)
Installed: reference:file:/home/renan/InstalledApps/docear-1.2.0.0_stable_build291/plugins/org.freeplane.plugin.bugreport (id#8)
Installed: reference:file:/home/renan/InstalledApps/docear-1.2.0.0_stable_build291/plugins/org.docear.plugin.services (id#9)
Installed: reference:file:/home/renan/InstalledApps/docear-1.2.0.0_stable_build291/plugins/org.freeplane.plugin.workspace (id#10)
Installed: reference:file:/home/renan/InstalledApps/docear-1.2.0.0_stable_build291/plugins/org.freeplane.plugin.latex (id#11)
Installed: reference:file:/home/renan/InstalledApps/docear-1.2.0.0_stable_build291/plugins/org.docear.plugin.pdfutilities (id#12)
Started: reference:file:/home/renan/InstalledApps/docear-1.2.0.0_stable_build291/plugins/org.freeplane.plugin.script (id#2)
Started: reference:file:/home/renan/InstalledApps/docear-1.2.0.0_stable_build291/plugins/org.freeplane.plugin.openmaps (id#3)
Started: reference:file:/home/renan/InstalledApps/docear-1.2.0.0_stable_build291/plugins/org.docear.plugin.core (id#4)
Started: reference:file:/home/renan/InstalledApps/docear-1.2.0.0_stable_build291/plugins/org.freeplane.plugin.formula (id#5)
Started: reference:file:/home/renan/InstalledApps/docear-1.2.0.0_stable_build291/plugins/org.freeplane.plugin.svg (id#6)
Started: reference:file:/home/renan/InstalledApps/docear-1.2.0.0_stable_build291/plugins/org.docear.plugin.bibtex (id#7)
Started: reference:file:/home/renan/InstalledApps/docear-1.2.0.0_stable_build291/plugins/org.freeplane.plugin.bugreport (id#8)
Started: reference:file:/home/renan/InstalledApps/docear-1.2.0.0_stable_build291/plugins/org.docear.plugin.services (id#9)
Started: reference:file:/home/renan/InstalledApps/docear-1.2.0.0_stable_build291/plugins/org.freeplane.plugin.workspace (id#10)
Started: reference:file:/home/renan/InstalledApps/docear-1.2.0.0_stable_build291/plugins/org.freeplane.plugin.latex (id#11)
Started: reference:file:/home/renan/InstalledApps/docear-1.2.0.0_stable_build291/plugins/org.docear.plugin.pdfutilities (id#12)
Mar 27, 2021 10:40:49 PM org.freeplane.core.util.LogUtils info
INFO: language resources for en found
Mar 27, 2021 10:40:49 PM org.freeplane.core.util.LogUtils info
INFO: freeplane_version = 1.3.2 alpha; freeplane_xml_version = freeplane 1.3.0
git revision = 547e9af_Anwender_2015-08-021946550200
java_version = 11.0.10; os_name = Linux; os_version = 5.8.0-48-generic
Mar 27, 2021 10:40:52 PM org.freeplane.core.util.LogUtils info
INFO: added parsing support for standard date format dd/MM/y
Mar 27, 2021 10:40:52 PM org.freeplane.core.util.LogUtils info
INFO: added parsing support for standard date time format dd/MM/y, HH:mm
Mar 27, 2021 10:40:55 PM org.freeplane.core.util.LogUtils info
INFO: Workspace controller installed.
Mar 27, 2021 10:40:55 PM org.freeplane.core.util.LogUtils info
INFO: org.docear.plugin.core.CoreConfiguration() initializing...
Mar 27, 2021 10:40:55 PM org.freeplane.core.util.LogUtils info
INFO: Docear version: 1.2.0.0 stable build 291
Mar 27, 2021 10:40:55 PM org.freeplane.core.util.LogUtils info
INFO: OS version: Linux 5.8.0-48-generic amd64
Mar 27, 2021 10:40:55 PM org.freeplane.core.util.LogUtils info
INFO: Loaded properties from bundle://4.0:0/org/docear/plugin/core/defaults.properties
Mar 27, 2021 10:40:55 PM org.freeplane.core.util.LogUtils info
INFO: Docear Core controller extension initiated.
Mar 27, 2021 10:40:55 PM org.freeplane.core.util.LogUtils info
INFO: Docear Services controller extension initiated.
Mar 27, 2021 10:40:56 PM org.freeplane.core.util.LogUtils info
INFO: Loaded properties from bundle://2.0:0/org/freeplane/plugin/script/defaults.properties
Mar 27, 2021 10:40:56 PM org.freeplane.core.util.LogUtils info
INFO: Loaded properties from bundle://5.0:0/org/freeplane/plugin/formula/defaults.properties
Mar 27, 2021 10:40:56 PM org.freeplane.core.util.LogUtils info
INFO: Loaded properties from bundle://9.0:0/org/docear/plugin/services/defaults.properties
Mar 27, 2021 10:40:56 PM org.freeplane.core.util.LogUtils info
INFO: Workspace settings not found, create new file
Mar 27, 2021 10:40:56 PM org.freeplane.core.util.LogUtils info
INFO: Docear Service feature installed: org.docear.plugin.services.features.user.workspace.DocearWorkspaceSettings
Mar 27, 2021 10:40:57 PM org.freeplane.core.util.LogUtils info
INFO: Docear Service feature installed: org.docear.plugin.services.features.io.DocearConnectionProvider

STDERR: java.lang.NoClassDefFoundError: org/omg/CORBA/portable/UnknownException
STDERR:         at org.docear.plugin.services.features.user.DocearUserController.<init>(DocearUserController.java:42)
STDERR:         at org.docear.plugin.services.ServiceController.initialize(ServiceController.java:86)
STDERR:         at org.docear.plugin.services.Activator.startService(Activator.java:29)
STDERR:         at org.docear.plugin.core.Activator.startPluginServices(Activator.java:67)
STDERR:         at org.docear.plugin.core.Activator.startPlugin(Activator.java:35)
STDERR:         at org.freeplane.plugin.workspace.Activator.startPluginServices(Activator.java:83)
STDERR:         at org.freeplane.plugin.workspace.Activator$2.installExtension(Activator.java:45)
STDERR:         at org.freeplane.main.osgi.ActivatorImpl.startFramework(ActivatorImpl.java:208)
STDERR:         at org.freeplane.main.osgi.ActivatorImpl.start(ActivatorImpl.java:79)
STDERR:         at org.freeplane.main.osgi.Activator.start(Activator.java:36)
STDERR:         at org.knopflerfish.framework.BundleImpl.start0(BundleImpl.java:374)
STDERR:         at org.knopflerfish.framework.PermissionOps.callStart0(PermissionOps.java:215)
STDERR:         at org.knopflerfish.framework.BundleImpl.start(BundleImpl.java:321)
STDERR:         at org.knopflerfish.framework.StartLevelImpl.increaseStartLevel(StartLevelImpl.java:285)
STDERR:         at org.knopflerfish.framework.StartLevelImpl$1.run(StartLevelImpl.java:217)
STDERR:         at org.knopflerfish.framework.StartLevelImpl.run(StartLevelImpl.java:178)
STDERR:         at java.base/java.lang.Thread.run(Thread.java:834)
STDERR: Caused by: java.lang.ClassNotFoundException: org.omg.CORBA.portable.UnknownException
STDERR:         at org.knopflerfish.framework.BundleClassLoader.findClass(BundleClassLoader.java:339)
STDERR:         at org.knopflerfish.framework.BundleClassLoader.loadClass(BundleClassLoader.java:438)
STDERR:         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
STDERR:         ... 17 more
STDOUT: ## DEBUG: errors - FrameworkErrorEvent bundle #1
STDOUT: ## DEBUG: errors - FrameworkErrorEvent throwable: 
STDERR: org.osgi.framework.BundleException: BundleActivator start failed
STDERR:         at org.knopflerfish.framework.BundleImpl.start0(BundleImpl.java:419)
STDERR:         at org.knopflerfish.framework.PermissionOps.callStart0(PermissionOps.java:215)
STDERR:         at org.knopflerfish.framework.BundleImpl.start(BundleImpl.java:321)
STDERR:         at org.knopflerfish.framework.StartLevelImpl.increaseStartLevel(StartLevelImpl.java:285)
STDERR:         at org.knopflerfish.framework.StartLevelImpl$1.run(StartLevelImpl.java:217)
STDERR:         at org.knopflerfish.framework.StartLevelImpl.run(StartLevelImpl.java:178)
STDERR:         at java.base/java.lang.Thread.run(Thread.java:834)
STDERR: Caused by: java.lang.NoClassDefFoundError: org/omg/CORBA/portable/UnknownException
STDERR:         at org.docear.plugin.services.features.user.DocearUserController.<init>(DocearUserController.java:42)
STDERR:         at org.docear.plugin.services.ServiceController.initialize(ServiceController.java:86)
STDERR:         at org.docear.plugin.services.Activator.startService(Activator.java:29)
STDERR:         at org.docear.plugin.core.Activator.startPluginServices(Activator.java:67)
STDERR:         at org.docear.plugin.core.Activator.startPlugin(Activator.java:35)
STDERR:         at org.freeplane.plugin.workspace.Activator.startPluginServices(Activator.java:83)
STDERR:         at org.freeplane.plugin.workspace.Activator$2.installExtension(Activator.java:45)
STDERR:         at org.freeplane.main.osgi.ActivatorImpl.startFramework(ActivatorImpl.java:208)
STDERR:         at org.freeplane.main.osgi.ActivatorImpl.start(ActivatorImpl.java:79)
STDERR:         at org.freeplane.main.osgi.Activator.start(Activator.java:36)
STDERR:         at org.knopflerfish.framework.BundleImpl.start0(BundleImpl.java:374)
STDERR:         ... 6 more
STDERR: Caused by: java.lang.ClassNotFoundException: org.omg.CORBA.portable.UnknownException
STDERR:         at org.knopflerfish.framework.BundleClassLoader.findClass(BundleClassLoader.java:339)
STDERR:         at org.knopflerfish.framework.BundleClassLoader.loadClass(BundleClassLoader.java:438)
STDERR:         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
STDERR:         ... 17 more
STDOUT: Nested bundle exception:
STDERR: java.lang.NoClassDefFoundError: org/omg/CORBA/portable/UnknownException
STDERR:         at org.docear.plugin.services.features.user.DocearUserController.<init>(DocearUserController.java:42)
STDERR:         at org.docear.plugin.services.ServiceController.initialize(ServiceController.java:86)
STDERR:         at org.docear.plugin.services.Activator.startService(Activator.java:29)
STDERR:         at org.docear.plugin.core.Activator.startPluginServices(Activator.java:67)
STDERR:         at org.docear.plugin.core.Activator.startPlugin(Activator.java:35)
STDERR:         at org.freeplane.plugin.workspace.Activator.startPluginServices(Activator.java:83)
STDERR:         at org.freeplane.plugin.workspace.Activator$2.installExtension(Activator.java:45)
STDERR:         at org.freeplane.main.osgi.ActivatorImpl.startFramework(ActivatorImpl.java:208)
STDERR:         at org.freeplane.main.osgi.ActivatorImpl.start(ActivatorImpl.java:79)
STDERR:         at org.freeplane.main.osgi.Activator.start(Activator.java:36)
STDERR:         at org.knopflerfish.framework.BundleImpl.start0(BundleImpl.java:374)
STDERR:         at org.knopflerfish.framework.PermissionOps.callStart0(PermissionOps.java:215)
STDERR:         at org.knopflerfish.framework.BundleImpl.start(BundleImpl.java:321)
STDERR:         at org.knopflerfish.framework.StartLevelImpl.increaseStartLevel(StartLevelImpl.java:285)
STDERR:         at org.knopflerfish.framework.StartLevelImpl$1.run(StartLevelImpl.java:217)
STDERR:         at org.knopflerfish.framework.StartLevelImpl.run(StartLevelImpl.java:178)
STDERR:         at java.base/java.lang.Thread.run(Thread.java:834)
STDERR: Caused by: java.lang.ClassNotFoundException: org.omg.CORBA.portable.UnknownException
STDERR:         at org.knopflerfish.framework.BundleClassLoader.findClass(BundleClassLoader.java:339)
STDERR:         at org.knopflerfish.framework.BundleClassLoader.loadClass(BundleClassLoader.java:438)
STDERR:         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
STDERR:         ... 17 more
STDOUT: Framework launched^C^C          
```

**Comment by qwertyuser1983** [comment]
Solved by installing Java 7, from https://github.com/BeelGroup/Docear-Desktop/issues/517. 

In my case, I am using https://cdn.azul.com/zulu/bin/zulu7.44.0.11-ca-jdk7.0.292-linux_amd64.deb

This issue is solved, thanks a lot.
